### PR TITLE
Configuration: Auto-reload when saving

### PR DESCRIPTION
**Pull request by tatchi**
My attempt to implement  #366

It should work but I'm not sure I've done it the best way so don't hesitate if you see any improvement.

### CODE REVIEW

**Comment by bryphe** [comment]
Looks great @tatchi !

Just tried it out on Windows and Mac:
configuration-reload

So much nicer than before 😍 Thanks for the contribution!

**Comment by bryphe** [comment]
Looks like there was a warning during build which caused the CI to fail:
```
Error: This expression has type unit -> unit
       but an expression was expected of type unit
       because it is in the left-hand side of a sequence
       Hint: Did you forget to provide `()' as argument?
```

(The `Vim.AutoCommands.onDispatch` returns a function that you can call if you want to unsubscribe - which we don't need to worry about this case, we'll subscribe for the lifetime of the app. But I added a `let _ = ` to suppress the error)

I pushed that change up - will bring this in once it's green -

**Comment by tatchi** [comment]
Thanks,

The CI still fails but I don't really understand why and if it's related to the code.

Do you have any idea?

**Comment by bryphe** [comment]
@tatchi - I just checked it out, it looked unrelated to the code - seems there were some '502' errors coming from NPM when installing packages (maybe related to the cloudflare outage yesterday).

Kicked it off again and it passed now - will bring it in now. Thank you for the contribution!

**Pull request merged**
