### PR TITLE
refactor(ux): combine ui fonts into a single family

### PR DESCRIPTION
**Pull request by glennsl**
Also updates to the latest version of revery, with a breaking change for the `Image` component to support remote images.

### CODE REVIEW

**Comment by glennsl** [comment]
`create-release` fails on mac with:

```
Found a dynamic library: ["libcrypto.1.1.dylib","libssl.1.1.dylib"]
There should be only static libraries to successfully package.
```

**Comment by glennsl** [comment]
I've tried to build `esy-openssl` using `-static` on macOS (see https://github.com/reason-native-web/vendor/compare/master...glennsl:esy-openssl/build/static), but unfortunately get this error:

    ld: library not found for -lcrt0.o

Googling that error led me to [this SO post](https://stackoverflow.com/a/3801032) which claims this is not possible on macOS.

Not sure how to proceed here other than to revise the strategy of trying to statically link everything on macOS.

**Comment by bryphe** [comment]
Thanks for making this change, @glennsl ! Much more streamlined 🎉 

> Not sure how to proceed here other than to revise the strategy of trying to statically link everything on macOS.

I'll investigate this today. The main concern is hitting issues like https://github.com/onivim/oni2/issues/1397 - crashes on boot for _some_ users.

 I think we have a good understanding now (for some reason, `libffi` was being flagged and quarantined by AV) - so we can potentially bring in `libcrypto` and `libssl` as dependencies. I'd like to at least test and verify we don't hit the same issue, though - ideally run the AV software on CI so we can ensure that our packaged builds won't be falsely flagged or hit a quarantine issue.

**Comment by bryphe** [comment]
FYI - I split out the upgrade / codesigning changes here: https://github.com/onivim/oni2/pull/1900

**Comment by bryphe** [comment]
I've hooked up the code-signing of those libraries, and validated that it at least isn't hitting the issue in #1397 - so should be unblocked now.

**Pull request merged**
