### PR TITLE
Update Esy Version Required

### PR DESCRIPTION
**Pull request by leematos**
0.6.0 is the latest version currently available. I currently am looking to try building and it appears 0.6.2 is not a thing yet?

Not sure what the right answer is, but making an assumption here :)

### CODE REVIEW

**Comment by bryphe** [comment]
Hi @leematos ,

Thanks for the PR!

Did you see an error message when trying to install esy 0.6.2? (`npm install -g esy@0.6.2`).

I see 0.6.2 as the latest published version on NPM:
image

**Comment by leematos** [comment]
weird! I don't really use NPM so my flow following the docs was:

- Prerequisites
  - click link for esy https://esy.sh/
      - See that the website shows 0.6.0 as latest
     - Look at repo releases and tags: https://github.com/esy/esy/releases 
        - See 0.6.1 as listed, but conflicting with esy website

Install 0.6.0, and I'm doing a build now, and submitted this PR to try and coalesce the difference. If 0.6.2 is real and npm installable, It could help to update the docs to just point to the npm install command instead?

**Comment by bryphe** [comment]
Oh, interesting, good point... I think those must be out-of-date. 

I logged an issue on the esy repo to track: https://github.com/esy/esy/issues/1064

**Comment by bryphe** [comment]
And ya, perhaps updating the documentation to show the install command directly - `npm install -g esy@0.6.2` would be clearer.

**Comment by leematos** [comment]
Edited! <3

**Comment by bryphe** [comment]
Excellent, thank you @leematos !

**Pull request merged**
