### PR TITLE
Fix typo in MOTIVATION.md

### PR DESCRIPTION
**Pull request by imbsky**

### CODE REVIEW

**Comment by imbsky** [comment]
and in the document, it's correct to write tree-sitter as tree-sitter, not as Treesitter. (I guess)

**Comment by imbsky** [comment]
Signed 👍

**Comment by bryphe** [comment]
Thanks @imbsky - appreciate you fixing this!

...apparently I need a spell-checker in oni2 😬

**Comment by imbsky** [comment]
Haha 😅 It's great idea. but I sometimes write and speak more strange English. No worries!

**Pull request merged**
