### PR TITLE
fix: Tab bug

### PR DESCRIPTION
**Pull request by SeitaHigashi**
Fixed the problem that the left and right scroll directions are reversed on the trackpad.

When I was using onivim on my Mac, I noticed that the scrolling of the tabs was reversed to the left and right of the trackpad. This means that you are not aware that you are using a mouse that only scrolls up and down.
I can't check it with OS other than mac, so it would be helpful if you could check it.

### CODE REVIEW

**Comment by bryphe** [comment]
Thanks @SeitaHigashi , nice catch on the bug, and well done on the fix 👍 

I believe this should be a safe change on other platforms, as the `deltaX`/track-pad case is primarily OSX. I'll double-check on a Windows machine though.

**Comment by bryphe** [comment]
I confirmed on a windows machine w/ trackpad - same bug exists there :+1:

**Review by bryphe — APPROVED** [review]

**Comment by goetzc** [comment]
I have had this bug where the horizontal scrolling direction using trackpad is reversed, and after this fix, it's still reversed.

My system is Linux (libinput 1.16.4) and running Onivim 2 (0.5.9-nightly, f8b4933f). Vertical scrolling direction is correct, but horizontal is reversed. I'm using "natural scrolling" settings, but disabling this makes vertical scrolling direction incorrect and horizontal correct.

**Comment by despairblue** [comment]
> I have had this bug where the horizontal scrolling direction using trackpad is reversed, and after this fix, it's still reversed.
> 
> My system is Linux (libinput 1.16.4) and running Onivim 2 (0.5.9-nightly, f8b4933f). Vertical scrolling direction is correct, but horizontal is reversed. I'm using "natural scrolling" settings, but disabling this makes vertical scrolling direction incorrect and horizontal correct.

Is this for scrolling the buffers or the tab bar at the top? Because I think this fix is only for the tab bar.

For file buffers I also still have this.

**Comment by goetzc** [comment]
Oh, this is right, I was referring to the file buffers. Although the tab bar is scrolling in reverse horizontal direction too.

**Pull request merged**
