### PR TITLE
fix(technical/#1749): ballooning window size

### PR DESCRIPTION
**Pull request by glennsl**
**Issue:** Every time Oni2 was opened in a previous workspace the window size would grow from what was persisted before is some form of scaling was used.

**Defect:** The window size was persisted using pixel size, but restored using screen coordinates, which would have it grow by the scaling factor each time.

**Fix:** Add a function upstream in Revery to get the window size in screen coordinates and persist that instead.

### CODE REVIEW

**Comment by CrossR** [comment]
I'm still getting a growing window on Windows 10 with the current build from the portal (https://github.com/onivim/oni2/commit/fa0d3d691938bcc8c6dba79f44f5559634b7cd8c). Perhaps the fix was only Linux specific?

**Comment by CrossR** [comment]
As far as I can see, the the "raw" size and the size used in this PR are the same?

The raw size uses `w.metrics.size.width` which is set in `_getMetricsFromGlfwWindow`, which in turn calls `Sdl2.Window.getSize`, which is what the new method uses.

The docs for that SDL2 call implies we need to use something else: https://wiki.libsdl.org/SDL_GetWindowSize, so do we need to hook up and use `GetRendererOutputSize`?

**Comment by bryphe** [comment]
Thanks for looking into this, @CrossR !

I suspect there's a case with scaling not handled properly - either via `GDK_SCALE` or on a high-dpi windows display. Does your Windows 10 machine have display scaling?

**Comment by CrossR** [comment]
Yeah, its a 4K monitor with 150% scaling, so could be scaling or high-DPI issues.

**Comment by bryphe** [comment]
Cool, thanks @CrossR - I'm able to reproduce this on a Windows 10 device with scaling, and also on Linux with `GDK_SCALE` set

**Comment by glennsl** [comment]
I don't have a high-DPI monitor, so I'm pretty much just stabbing in the dark.

I can't see how something like `GetRendererOutputSize` would work though, as that returns pixel size. Assuming this still follows the conventional definition of pixel, as a representation of physical coordinates, there should be more pixels per "screen coordinate" with a high-DPI and/or a scale factor above 1.0. And since the problem is that the window grows, not shrinks, the problem seems to be that we're getting pixels and/or unscaled coordinates.

Could you run some tests with the reason-sdl2 example @CrossR so we can really figure out the relation between these coordinates?

**Comment by bryphe** [comment]
I can help with this @glennsl - I have setups to test on both Linux/Windows.

I think the main problem is inconsistency in the Revery `Window` API in talking about sizes - there are two window sizes that SDL gives us - the 'screen space' size, and the 'framebuffer' size. On top of that, we also account for display scaling (like frameworks like Electron handle). So that makes three 'spaces' for window sizes:
- 1) Framebuffer pixel size
- 2) Screen space size
- 3) Screen space size, with display scaling

The problem was, the API surface wasn't consistent in handling this - `create`, `getSize`, and `setSize` should all be consistent in the space they use - which they weren't. `create` would use coordinates in the 'display scaled' space (3), but getSize/getRawSize would get the dimensions in (2) - likewise with `setSize`.

I opened https://github.com/revery-ui/revery/pull/840 to try and clean up that API and clarify this... hopefully it helps.

**Pull request merged**
