### PR TITLE
Packaging: Additional fixes for Linux AppImage bundling

### PR DESCRIPTION
**Pull request by bryphe**

### CODE REVIEW

**Comment by probonopd** [comment]
Can the AppImage be downloaded somewhere? Would be neat to use something like https://github.com/probonopd/uploadtool to upload each build to GitHub Releases. Thanks!

**Comment by bryphe** [comment]
Hey @probonopd ! 

To start - I'm planning on adding a portal to https://v2.onivim.io to upload the Linux / Windows / Mac binaries (the early pre-alpha / alpha builds will be only available for users who pre-ordered, backers, etc). ETA for that is end of this month.

Longer term (once we have some sort of key validation strategy in the app), I'll make the builds more broadly available (as part of our 'MVP' release on the timeline: https://v2.onivim.io/#timeline).

**Comment by probonopd** [comment]
Any chance to get an AppImage for testing in the meantime?

**Comment by szbergeron** [comment]
I'd honestly recommend just building it as it's not a particularly involved process and will let you pull down the latest changes a lot quicker, but ymmv

**Pull request merged**
