### PR TITLE
Skia Integration

### PR DESCRIPTION
**Pull request by bryphe**
This integrates the latest Skia prototype build from the Revery branch here: https://github.com/revery-ui/revery/pull/567

That PR replaces our 'home grown' rendering library with [Skia](https://skia.org/) - a battle-tested and widely used 2D graphics framework (used by SublimeText, Chrome, Flutter, etc). This should help us in the following ways:
- More efficient text rendering (batching, texture atlasing)
- Better fidelity text rendering (subpixel / LCD rendering)
- Better performance for other drawing primitives

It actually is _sort of_ working with this PR:

Home screen:
image

Editor:
image

There are some issues we still need to address before its usable:
- [x] Image positioning is different (as seen by the logo placement on the welcome screen)
- [x] The `drawText` API seems to render at a different position (the lines are currently offset)
- [x] Scaling issues (with zoom / high - DPI - mouse coordinates are not correct)
- [x] Text rendering ligatures (we're not using the shape result of text currently)
- [x] Refactor `Minimap.drawRect` to an external utility
- [x] Test out `drawRectLtwh` perf
- [x] Fix zoom issue on Windows high DPI display
- [x] Get integration tests passing
- [x] Fix OSX `create-release`
- [x] Fix mouse coordinate resolution when clicking on surface
- [x] Verify release builds
- [x] Test / fix wayland (#1283 - thanks @szbergeron for your help testing!)
- [x] Fix PNG rendering on Linux (CentOS 7)
- [x] Fix tab character positioning
- [x] Fix text measurement issue on Linux (CentOS 7) - we're using `setSubpixelText(true)` to measure, but it isn't always respected. We should turn this off by default and enable as a configuration setting.
- [x] Test and improve performance. There are lots of places we can 'trim' now, and there might be even better ways to render the minimap than individual `drawRect` calls.

### CODE REVIEW

**Comment by bryphe** [comment]
The windows font measurement issue issue (which I mistakenly thought was a zoom issue) is fixed now: https://github.com/revery-ui/revery/pull/749

**Comment by szbergeron** [comment]
Seems to refer to a deleted Revery tag now (esy install fails because of this)

**Comment by szbergeron** [comment]
Seems unhappy for me :/

2020-02-04-115308_grim

**Comment by bryphe** [comment]
Did some profiling / perf-comparison. This was measured in the case of a stress-test (ie, small font size, lots of splits, full-screen - so lots of elements to render). 

__Pre-skia:__

| Operation | Avg Time |
| ---  |---- |
| Transform Recalculation | 6.3ms |
| Draw |  32.33 ms |
| __Total Render Time__ | __41.33 ms__ |

__Post-skia:__

| Operation | Avg Time |
| ---  |---- |
| Transform Recalculation | 7.22ms |
| Draw |  13.31 ms |
| __Total Render Time__ | __24.38 ms__ |

This is a very significant improvement already! Much faster to render a large complex scene - and if you consider that we are getting improved text fidelity on top of that... that's pretty impressive.

An interesting aspect is that the transform recalculation actually got more expensive with Skia. Prior to rendering, we recalculate the world transforms and bounding boxes for all the UI elements that have changed. We switched to using Skia's matrix representation (previously we had used [Glm](https://glm.g-truc.net/0.9.9/index.html)). 

This isn't actually a deficiency of Skia, though - I had spent time optimizing the C FFI for OCaml <-> GLM to minimize allocations, and we hadn't done that yet for Skia.

I have PRs in progress that haven't been reflected in these benchmarks:
https://github.com/revery-ui/reason-skia/pull/40
https://github.com/revery-ui/reason-skia/pull/43
https://github.com/revery-ui/reason-skia/pull/46
https://github.com/revery-ui/revery/pull/754

Once those are in place, I believe the `recalculate` phase will actually be faster with Skia. There are some functions it gave us in the C FFI like `mapRect` that mean less back-and-forth to calculate things like our bounding box transforms.

Likewise, I think there is still some performance headroom to improve the bindings for several heavy Skia APIs we use in the `draw` phase:
- `Canvas.drawText`
- `Canvas.drawRect`
- `Paint.set*`

So I'll be looking forward to see what kind of improvement we can get there. The goal ultimately is to get the entire render time under 16ms, to maintain 60 FPS and leave some headroom for other features.

**Comment by bryphe** [comment]
Build is green! 🎉 

I anticipate that there may be additional issues to work through - but I think it makes sense to bring this in now and work through those. 

We'll continue to build on and improve this foundation - it's a major evolutionary step for both Revery and Onivim 2!

**Comment by bryphe** [comment]
@glennsl - let me know if you need any help merging up with the work you were doing to refactor the EditorSurface 👍

**Pull request merged**
