### PR TITLE
feat(extensions): Add emmet extension

### LINKED ISSUE #1948: Emmet support
It would be great to have Emmet support in onivim2 as it's amazing how much it's relied on when writing jsx or html. This is built in to vscode rather than a plugin, so I'm not sure how onivim would integrate it?

(as part of the integration, it would be great to have the wrap with abbreviation functionality which is a big improvement over  vim surround's wrap with tag,
https://docs.emmet.io/actions/wrap-with-abbreviation/)

### PR DESCRIPTION
**Pull request by bryphe**
This adds the built in VSCode emmet extension (Emmet 2.0), and hooks it up.

There are a few additional features we need, though, to get it usable:
- [x] Handle the `isIncomplete` value from a completion provider - emmet sends this to tell the editor to continue to request completions. We don't handle it, currently. 
- [x] Proper snippet expansion - we have an extremely minimal snippet implementation, which means the expansion aren't too helpful
-  Completion documentation - there is no preview for the expansion, currently. (tracking in #2329 )

Fixes #1948

### CODE REVIEW

**Comment by yunti** [comment]
So excited for this one!

**Comment by Jorgee97** [comment]
Any updates on this?

**Comment by yunti** [comment]
I think this needed snippets feature which was just added in so hopefully this may be added soon.

**Comment by bryphe** [comment]
Yep, need to test it, but a few of the pieces are close to being in:
- Snippets: #3130 
- `isIncomplete` handling - fixed up some of the remaining issues in #3054 . Works for `clang` and `golang` but need to double-check the experience with emmet.

**Comment by iryan2** [comment]
Does this include Emmet for CSS?

**Comment by fiddler** [comment]
Excited for this one, major coder life quality improvement! 🥳

**Comment by bryphe** [comment]
Actually seems like it is working pretty well:



It helps to have these settings added:
```
"emmet.showSuggestionsAsSnippets": true,
"editor.snippetSuggestions": "top"
```
to ensure the emmet-expansion suggestions take priorities over other ones (like keywords)

There's a little more work needed to show a preview of the expansion (the completion UI needs some TLC: https://github.com/onivim/oni2/pull/2329), but I'll bring this in as-is so we can start testing it and exercising the snippet integration

**Pull request merged**
