### PR TITLE
feat(buffers/#3413) Implement action.workbench.quickOpenBuffer

### PR DESCRIPTION
**Pull request by aubinlrx**
Implement feature for #3413

```changelog
Add new command `action.workbench.quickOpenBuffer` to easily navigate through buffers
```

### CODE REVIEW

**Comment by aubinlrx** [comment]
This is my firs PR on `onivim/oni2` repo. Don't hesitate to give guidance on what's missing. I didn't included keybindings since it's not standard in vim. But i've locally bound `<leader>pb`. It works perfectly.

**Comment by jesstelford** [comment]
Whoa, that's fantastic! Great work 🎉

**Review by bryphe — APPROVED** [review]
Thanks @aubinlrx for taking this on! The fix looks great 👍 

Just made a couple minor tweaks:
- Added an entry in the menubar for this functionality
- Added a CHANGES entry

Will merge this when CI is green

**Comment by bryphe** [comment]
Just looked again -
- The Linux CI failures are due to a bug in cache restore - not due to these changes - so I'll bypass
- The CLA isn't required, since the contributed change is under our threshold.

Merging now - will be in the `0.5.6` release - thanks @aubinlrx for the awesome contribution!

**Pull request merged**
