### PR TITLE
fix: Correctly handle go to definition on Windows

### PR DESCRIPTION
**Pull request by Sloff**
This resolves issue #1343, but I'm unable to test it on Linux or Mac

### CODE REVIEW

**Comment by bryphe** [comment]
Wow, this is awesome @Sloff , thank you for investigating and fixing this!

I tested on Mac - still works. I added a unit test to document the behavior, and confirmed it's still working on Windows / OSX after the change.

**Comment by bryphe** [comment]
Looked at the CI failure - looks like one of our integration tests is failing with this change - the `LanguageCssTest`:

```
[INFO]   +101ms IntegrationTest :  WAITER (Validate a diagnostic showed up, since our current input is erroneous): Finished - result: false
[INFO]     +0ms IntegrationTest :  WAITER (Validate a diagnostic showed up, since our current input is erroneous): FAILED: D:\oni2\_esy\integrationtest\store\i\oni2-799ad8f9\bin\LanguageCssTest.exe
[ERROR]    +1ms Oni2.Exception : Exception "Assert_failure integration_test/lib/Oni_IntegrationTestLib.re:174:6":
Raised at file "integration_test/lib/Oni_IntegrationTestLib.re", line 174, characters 6-28
Called from file "integration_test/LanguageCssTest.re", line 57, characters 2-396
Called from file "integration_test/lib/Oni_IntegrationTestLib.re", line 179, characters 2-56
Called from file "integration_test/LanguageCssTest.re", line 10, characters 0-1023
```

I can reproduce it locally on Windows with `esy '@integrationtest' x LanguageCssTest.exe`.

**Comment by bryphe** [comment]
I can reproduce this locally too - if I create a file `test.css` like: 
```
body {};
```

I'll get an error on `master` of "Do not use empty rulesets", but no error with this PR.

The diagnostics also use a URI to match up buffers / diagnostics from the extension host.

**Comment by Sloff** [comment]
Thanks @bryphe for pointing me in the right direction. I've rather altered the code to only remove the leading slash when calling `toFileSystemPath`. With this Go To Definitions works on Windows, as well as the error message displays in the `.css` file.

**Comment by bryphe** [comment]
Excellent! Thanks for the fix and the help @Sloff - works great!

**Pull request merged**
