### PR TITLE
feat(terminal/#2298): Implement toggleable terminal

### LINKED ISSUE #2298: Terminal: Ability to toggle a terminal
A cool feature VSCode has is the ability to toggle a terminal <kbd>Control</kbd>+<kbd>`</kbd>. In some cases, for running a quick command - this can be more ergonomic than opening / closing a split. This would be a nice feature to have in Onivim as well.

### PR DESCRIPTION
**Pull request by bryphe**
A common feature request I've gotten is #2298 - the ability to toggle a terminal with <kbd>Control</kbd><kbd>`</kbd>.

This PR implements some refactoring for the 'pane' to make it easier to add pane sections, like an integrated terminal, and then adds a pane section for the terminal:

image

Note that this doesn't change anything around how `:term` behaves

Fixes #2298 

__TODO:__
- [x] Bring back cycling pane tabs
- [x] Bring back custom pane buttons
- [x] Bring back normal-mode toggle in terminal
- [x] Fix up test cases
- [x] Fix terminal font in integrated terminal
- [x] Investigate crash when resizing terminal (https://github.com/revery-ui/esy-libvterm/pull/6 https://github.com/revery-ui/revery-terminal/pull/30)

### CODE REVIEW

**Comment by likern** [comment]
🎉👍 I couldn't find keybinding how to open exact pane section - in my case "Locations". And how to iterate over that sections.

Also looks like Sneak mode is broken, at least for Typescript project. And doesn't show letters for pane sections

**Comment by bryphe** [comment]
Hi @likern ,

Thanks for testing this out!

> I couldn't find keybinding how to open exact pane section - in my case "Locations". And how to iterate over that sections.

The default binding for this is `Shift+F12`:



> Also looks like Sneak mode is broken, at least for Typescript project. And doesn't show letters for pane sections

Ah, thanks, I fixed the pane section issue in this PR. For the typescript project - what sort of sneak mode items were missing? Items in the editor?

**Comment by likern** [comment]
> Hi @likern ,
> 
> Thanks for testing this out!
> 
> > I couldn't find keybinding how to open exact pane section - in my case "Locations". And how to iterate over that sections.
> 
> The default binding for this is `Shift+F12`:
> 
> 
> 
> > Also looks like Sneak mode is broken, at least for Typescript project. And doesn't show letters for pane sections
> 
> Ah, thanks, I fixed the pane section issue in this PR. For the typescript project - what sort of sneak mode items were missing? Items in the editor?

It looks like sneak elements are shown not in correct positions. 

1. Entering in sneak mode I would expect that pane sections (like Locations) would also have attached tags
2. I think some tags (labels? What is an official terminology for this?) shown in incorrect positions or even invalid. I've attached video showing some of them.


https://user-images.githubusercontent.com/842306/117297735-39478480-ae7f-11eb-966e-1cc28e9506f5.mp4

**Comment by bryphe** [comment]
Hi @likern  -

Thanks for the details!

> Entering in sneak mode I would expect that pane sections (like Locations) would also have attached tags

This should be fixed in this PR:

image

(...although, the sneak-tag offsets could be improved to not occlude the labels...)

> I think some tags (labels? What is an official terminology for this?) shown in incorrect positions or even invalid. I've attached video showing some of them.

Ah, thanks - that helps clarify. There's a bug I'm tracking where 'stale' sneak-tags are shown in the UI: https://github.com/onivim/oni2/issues/2568 - I believe this is another manifestation of it.

**Pull request merged**
