### PR TITLE
Added syntax highlighting for golang

### PR DESCRIPTION
**Pull request by NinoFurger**
As requested here: #601 
I tried it a bit and the syntax highlighting seems to work for me.

### CODE REVIEW

**Comment by bryphe** [comment]
Thanks for bringing this in, @NinoFurger ! Looking into the build failure now - doesn't seem like it's a result of your changes.

I'll kick off the build again just to check-

**Comment by bryphe** [comment]
Green this time around 😄 Bringing this in now - thanks again @NinoFurger !

**Comment by cnguy** [comment]
Wanted to mention this: thank you all! I'll be using this. :) I already use Onivim for Python-related projects.

**Comment by bryphe** [comment]
@cnguy - awesome! 😄 

It looks like there are tree-sitter grammars for Python and Go:
- https://github.com/tree-sitter/tree-sitter-python
- https://github.com/tree-sitter/tree-sitter-go

Will be nice if we can get those integrated w/ the tree-sitter work that is happening

**Pull request merged**
