### PR TITLE
feat(editor/#966): Customizable line height

### LINKED ISSUE #966: Is line-height option supported?

### PR DESCRIPTION
**Pull request by bryphe**
This adds customization for the line height on the editor surface, defaulting to `1.2` times the font height for a little extra breathing room:

Fixes #966

### CODE REVIEW

**Comment by DanielPower** [comment]
To be compatible with VS Code configs, line height should be a float which is a multiplier of the font size, rather than a pixel value.

**Comment by bryphe** [comment]
@DanielPower - actually, AFAIK, the `editor.lineHeight` setting in VSCode is actually an absolute size. There's some confusion with this, actually (many users expect it to be proportional vs absolute):
https://github.com/microsoft/vscode/issues/33968

What's really confusing is there are also `markdown.preview.lineHeight` and `terminal.integrated.lineHeight` which _are_ proportional multipliers...

We actually support both (not documented) using:
```
"editor.lineHeight": { "proportional": 1.5 }, // Line size 1.5 times the font height
"editor.lineHeight": { "absolute": 20 }, // Line size is 20 pixels
"editor.lineHeight": 30, // Line size is 30 pixels - functionally equivalent to `{"absolute": 30}`.
```

**Comment by DanielPower** [comment]
You're totally right. When I did a WIP implementation of this I did it using a multiplier, which it turns out was incorrect. Sorry to waste your time on that 😅

The additional option of specifying proportional is great to have. Thank you for this feature! I've been back on Neovim for a while, but will check out Onivim2 again soon, it seems to be shaping up.

**Comment by bryphe** [comment]
Haha, no worries - it is very confusing 😄 

> but will check out Onivim2 again soon, it seems to be shaping up.

Awesome! Feel free to log issues or let me know what is missing in your workflow 👍

**Comment by taylorthurlow** [comment]
This is a huge usability change for me, thanks for your hard work!

**Pull request merged**
