### PR TITLE
fix(editor): Fix exception in BufferLine.getPositionAndWidth with negative index

### PR DESCRIPTION
**Pull request by bryphe**

### CODE REVIEW

**Comment by zbaylin** [comment]
Im curious, how did you come across this? I think I experienced it once with a Hover crash but I couldn't replicate it ever again.

**Comment by bryphe** [comment]
> Im curious, how did you come across this? I think I experienced it once with a Hover crash but I couldn't replicate it ever again.

Hmm, ya, I was experiencing some intermittent crashes:
```
[ERROR]    +7ms Oni2.Exception : Exception (Invalid_argument "index out of bounds"):
Raised by primitive operation at file "src/Core/BufferLine.re", line 198, characters 11-30
Called from file "src/Feature/Editor/Editor.re", line 84, characters 6-108
Called from file "src/Feature/Hover/Feature_Hover.re", line 371, characters 10-211
Called from file "src/UI/EditorView.re", line 94, characters 10-420
Called from file "src/Feature/Editor/EditorSurface.re", line 314, characters 4-34
Called from file "lib/Brisk_reconciler_internal.re", line 831, characters 12-205
Called from file "lib/Brisk_reconciler_internal.re", line 735, characters 12-235
Called from file "lib/Brisk_reconciler_internal.re", line 1346, characters 14-401
Called from file "lib/Brisk_reconciler_internal.re", line 1090, characters 16-497
Called from file "lib/ListTR.re", line 32, characters 22-40
Called from file "lib/Brisk_reconciler_internal.re", line 1067
```

I figured it might've been related to my change here: https://github.com/onivim/oni2/blame/master/src/Feature/Hover/Feature_Hover.re - the only case I think of that would hit the callstack would be somehow getting a negative character index.

**Comment by zbaylin** [comment]
Makes sense! It appeared for me around the same time as the completion being off-positioned.

**Comment by bryphe** [comment]
> Makes sense! It appeared for me around the same time as the completion being off-positioned.

Yep, same change was responsible for that 😅

**Pull request merged**
